In [19]:
%load_ext autoreload
%autoreload 2
# Set-up: Import numpy and assign GPU
%matplotlib inline

import os
os.environ['TRANSFORMERS_CACHE'] = '/local/helenl/.cache/'
os.environ['PYTORCH_TRANSFORMERS_CACHE'] = '/local/helenl/.cache/'

import numpy as np
import scipy as sp
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn
from tqdm.notebook import tqdm

from gpu_utils import restrict_GPU_pytorch
from helenl_utils import *
from matplot_figure_format import *
from transforms_helenl import *
from path_stop import *

restrict_GPU_pytorch('3')

import statistics
import sys
import pickle
import numpy as np
import pandas as pd
import statistics
import json
import random


import torch
import torchvision.transforms as transforms

import argparse
import pdb


from wordcloud import WordCloud
import itertools

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Using GPU:3


In [2]:
def create_corrections_corruptions_plots(df, title = ''):
    
    sns.set(font_scale = 2)
    fig, ax = plt.subplots()
    
    df_melted = df.reset_index().melt(id_vars = 'augmentation')
    df_melted = df_melted[df_melted.variable != 'index']

    print(df_melted)
    
    min_value = df_melted.min()["value"]
    max_value = df_melted.max()["value"]

    ax.set_ylim(min_value - 100, max_value + 100)


    #show_values(p)
    plt.rcParams['figure.figsize'] = (80,20)

    ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha='right')

    plt.title(title)

    

    #sns.set(rc = {'figure.figsize':(30,10)})
    p = sns.barplot(x = 'augmentation', y = 'value', hue = 'variable', data = df_melted, ci = False, palette = ["green", "red"])#, order = acc_df['augmentation'])

    show_values(p)


    plt.show()

    

In [20]:
#full_dataset = get_dataset(dataset='civilcomments', download=False, root_dir = './wilds/data')

predict_augmented_labels("nlp_random_word_delete"
                            , "civilcomments"
                            , "ERM"
                            , OUTPUT_PATH
                            , full_dataset
                            , num_samples = 4
                            , aug_char_min = 1
                            , aug_char_max = 1
                            , aug_char_p = 1
                            , aug_word_min = 1
                            , aug_word_max = None
                            , aug_word_p = 0.1
                            , aug_sentence_min = 1
                            , aug_sentence_max = None
                            , aug_sentence_p = 0.1
                            , min_char = 4)

predict_augmented_labels() num_samples: 4
initialize_transform() num_samples: 4
char_min: 1
word_p: 0.1
initialize_bert_transform() num_samples: 4
initialize_transform() num_samples: 4
char_min: 1
word_p: 0.1
initialize_bert_transform() num_samples: 4
nlp_random_word_delete
initialize model


Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertClassifier: ['vocab_transform.bias', 'vocab_projector.bias', 'vocab_layer_norm.bias', 'vocab_layer_norm.weight', 'vocab_projector.weight', 'vocab_transform.weight']
- This IS expected if you are initializing DistilBertClassifier from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertClassifier from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of DistilBertClassifier were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN t

initialization complete
generating predictions


  0%|          | 0/16723 [00:00<?, ?it/s]

batch: [[tensor([[[  101,     1],
         [ 2821,     1],
         [ 2748,     1],
         ...,
         [    0,     0],
         [    0,     0],
         [    0,     0]],

        [[  101,     1],
         [ 2002,     1],
         [ 1005,     1],
         ...,
         [    0,     0],
         [    0,     0],
         [    0,     0]],

        [[  101,     1],
         [ 3393,     1],
         [ 2721,     1],
         ...,
         [    0,     0],
         [    0,     0],
         [    0,     0]],

        ...,

        [[  101,     1],
         [ 9951,     1],
         [ 1010,     1],
         ...,
         [    0,     0],
         [    0,     0],
         [    0,     0]],

        [[  101,     1],
         [ 1998,     1],
         [ 2009,     1],
         ...,
         [    0,     0],
         [    0,     0],
         [    0,     0]],

        [[  101,     1],
         [ 1996,     1],
         [21003,     1],
         ...,
         [    0,     0],
         [    0,     0],
        

In [24]:
file = OUTPUT_PATH + 'civilcomments_ERM_predictions_optimized_params_four_samples/raw/nlp_random_word_delete.npy'

with open(file, 'rb') as aug_file:
    aug_logit_predictions = np.load(aug_file, allow_pickle = True)
    aug_labels = np.load(aug_file, allow_pickle = True)
    metadata = np.load(aug_file, allow_pickle = True)
    
print(aug_logit_predictions)
print(np.shape(aug_logit_predictions))

print(aug_labels)
print(np.shape(aug_labels))

print(metadata[:12])
print(np.shape(metadata))

[[-0.0806791  -0.0148583 ]
 [ 2.18063664 -2.48713326]
 [ 1.78217852 -2.05658937]
 ...
 [ 0.89004332 -1.01642132]
 [-0.26282683  0.16945408]
 [ 0.52655756 -0.67368942]]
(535128, 2)
[1 0 0 ... 0 0 0]
(535128,)
[[0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 1 0 0 0 1 1 1 1 0]
 [0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0]
 [0 0 0 0 1 0 1 1 1 0 0 0 1 1 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0]]
(535128, 17)


In [ ]:
def calculate_4_sample_corrections_corruptions(aug_pred_file, original_pred_file):
    """
    operating under data structure of:
        predictions = [logit_input_1_sample_1
                      , logit_input_1_sample_2
                      , logit_input_1_sample_3
                      , logit_input_1_sample_4
                      , ...]
                      
        labels = [sample_1_label
                  , sample_1_label
                  , sample_1_label
                  , sample_1_label
                  , sample_2_label
                  , ...]
    
    """
    
    
    aug_logit_predictions = []
    aug_classified_predictions = []
    
    original_logit_predictions = []
    original_classified_predictions = []
    
    aug_labels = []
    original_labels = []
    
    with open(aug_pred_file, 'rb') as aug_file:
        aug_logit_predictions = np.load(aug_file, allow_pickle = True)
        aug_labels = np.load(aug_file, allow_pickle = True)
    
    with open(original_pred_file, 'rb') as original_file:
        original_logit_predictions = np.load(original_file, allow_pickle = True)
        original_labels = np.load(original_file, allow_pickle = True)
        
    assert aug_labels.all() == original_labels.all(), "Test set labels do not match between aug. and original."
    assert aug_labels.size == original_labels.size
    
    for prediction in aug_logit_predictions:
        index_prediction = np.argmax(prediction).tolist()
        
        aug_classified_predictions.append(index_prediction)
    
    for prediction in original_logit_predictions:
        index_prediction = np.argmax(prediction).tolist()
        
        original_classified_predictions.append(index_prediction)
    
    
    corrections_count = 0
    corrections_indices = []
    
    corruptions_count = 0
    corruptions_indices = []
    
    for i in range(len(aug_labels)):
        label = original_labels[i]
        original_pred = original_classified_predictions[i]
        aug_pred = aug_classified_predictions[i]
        
        
        # if corruption
        if (original_pred == label and aug_pred != label):
            corruptions_count += 1
            corruptions_indices.append(i)
        
        # if correction
        elif (original_pred != label and aug_pred == label):
            corrections_count += 1
            corrections_indices.append(i)
    
    corrections_corruptions_dict = {"num_corrections": corrections_count
                                    , "num_corruptions": corruptions_count
                                   , "corrections_indices": corrections_indices
                                   , "corruptions_indices": corruptions_indices}
    
    return corrections_corruptions_dict